### ISSUE TITLE
Integration with stack?

### ISSUE THREAD

**Issue by afcowie** [aloiscochard/codex#39]
Can we make use of the vast trove of information `stack` assembles to source code [rather than going to hackage, for example]?

AfC

**Comment by rgrinberg** [comment]
+1

**Comment by aloiscochard** [comment]
I have not used `stack` or looked into, so I'm not sure to understand what you mean?

You mean being able to customize https://github.com/aloiscochard/codex/blob/master/src/Codex/Internal.hs#L48 ?

Or accessing an other stack specific local storage?

**Comment by aloiscochard** [comment]
@rgrinberg @afcowie could you please shed some light on this one?

I'm still not clear what you would like to see as integration with `stack`?

**Comment by afcowie** [comment]
@aloiscochard So **stack** is a built tool, yeah? It's a replacement for **cabal-install** yes, but it adds a lot more capability in terms of managing the tree of packages you're building from.

When I tried **codex** in a project tree I was building with **stack**, it went out to Hackage directly to get packages. There are two problems with that:

1) the set of packages (specifically their versions) being used to actually successfully build are not the same as whatever the latest on Hackage is; and

2) the packages' source code was _already_ downloaded and cached by stack, so going to Hackage to get them again was a bit wasteful.

If you try using `stack build` in an existing project or two you'll quickly see what it's up to; I built **codex** with it :).

I'm sure @snoyberg et al could express it better than I am, but I think there are ways to ask **stack** to get what you need, perhaps more easily that the steps you're going through now.

Appreciate your time considering this!

AfC

**Comment by snoyberg** [comment]
There's likely other things that could be done here, but it sounds like there are two things that could be done:

1. Query `stack` to find out the version numbers of all packages in the build plan. We don't (to my knowledge) have a command to get that information yet, but it's trivial to add
2. Instead of downloading directly from Hackage, you could use the `stack unpack` command to get package contents, which will use the local cache

@afcowie Is that the kind of thing you were thinking of?

**Comment by afcowie** [comment]
@snoyberg I didn't even think of `stack unpack`. Perfect of course. Needs
the first part but as you say should be straight forward.

**Comment by snoyberg** [comment]
@aloiscochard If you're interesting this integration, let me know, and we can hash out how best to get you the list of dependencies.

**Comment by afcowie** [comment]
@aloiscochard are you interested in **codex** being able to pull from the package cache and dependency list that **stack** is able to provide?

**Comment by afcowie** [comment]
@aloiscochard Are you interested in **codex** being able to pull from the package cache and dependency list that **stack** is able to provide? I'm pretty sure everything you'd need is available already. Can you tell us what you need?

AfC

**Comment by aloiscochard** [comment]
@afcowie I have no idea what I need beside some time to look into it.

FWIW, I'm getting into stack this days, so hopefully I'll be able to have a better clue of how the integration should work.

Cheers

**Comment by aloiscochard** [comment]
@afcowie so, I just started using slack, and I can now clearly see why some integration is needed.

I have few questions regarding the integration.

First, from what I understand, stack maintain his hackage index in `~/.stack/indices/Hackage`, is that always the case? can I hard-code that path in `codex` to know where to query the hackage index (as a fallback from `cabal` one)? or is there a way to resolve that path using the `slack` binary (or even library) or something like that?

Second, `codex` expect the current project to be configured properly for `cabal`, but a `stack` project is not. So I need to know how you run cabal in slack project, do you add some argument to make it use the `.stack-work` directory?

Finally, how can I know that a given project is "stack" enabled? just by looking if the `.stack-work` directory exists?

Thanks in advance for your help

/cc @snoyberg

**Comment by jdnavarro** [comment]
@aloiscochard `stack` sets several environment global variables with different path info. You may be able to use them in `codex` to know whether you are running within `stack` and where are all the paths. This assumes `codex` for stack will be run `stack exec codex`, but perhaps you don't want that. As an end user of `stack` and `codex` I'm fine with that.

I'm guessing `ghc-mod` and `doctests` already went through this, so you might want to have a look at any commits related to `stack`.

**Comment by afcowie** [comment]
@snoyberg I'm going to guess you'd be able to answer @aloiscochard questions in https://github.com/aloiscochard/codex/issues/39#issuecomment-139548315 better than I. I'll take a guess, though:

* `stack path` outputs tons of stuff. Is what you need therein? If not, I daresay the **stack** hackers would be happy to add what you need.

* as @jdnavarro said, `stack exec ...` will get the environment variables set such that various `ghc` commands will operate with the correct `GHC_PACKAGE_PATH` (and hence correct databases).
* and finally, `stack unpack`, as mentioned before (if what you need isn't already unpacked out in _~/.stack_ somewhere).

AfC

**Comment by snoyberg** [comment]
Unfortunately, wrapping calls to `cabal` with `stack exec` doesn't work as nicely as you'd want, since cabal throws up its hands when `GHC_PACKAGE_PATH` is set. You'll need to explicit pass it `--package-db` flags to make it work. There's a Reddit thread that contains some information:

https://www.reddit.com/r/haskell/comments/3bw95a/using_cabal_and_stack_together/

It also has the following magical incantation from me:

    cabal configure --package-db=clear --package-db=global --package-db=$(stack path --snapshot-pkg-db) --package-db=$(stack path --local-pkg-db)

**Comment by begriffs** [comment]
When using Stack what settings should I specify in my `~/.codex` file? It currently looks like this

```yaml
hackagePath: .cabal-sandbox/packages/
tagsFileHeader: false
tagsFileSorted: false
tagsCmd: hasktags --extendedctag --ignore-close-implementation --ctags --tags-absolute --output='\$TAGS' '\$SOURCES'
```

But `hackagePath` references a cabal sandbox.

**Comment by aloiscochard** [comment]
@begriffs this is a known issue (which is actually this particular one we are discussion on).

I'm sorry that I had no time to work on it **yet**, but I'm finally less busy and I should be able to solve this by the end of the month.

Thanks for your understanding.

**Comment by aloiscochard** [comment]
@begriffs I've just published `codex-0.3.0.10`, this version include a fix so `codex` properly take into account the value defined as `hackagePath` in the configuration file.

Thanks to this fix, here is a temporary solution in order to use `stack` index instead of the default one from hackage, simply put this value in your `~/.codex`:
```
hackagePath: /home/alois/.stack/indices/Hackage/
```

Obviously you should change the home folder to match your own, I would like to emphasis that **this is a temporary solution**.

I'm working on a complete `stack` integration that I hope to release soon, but I feel like I would share this workaround for folks who don't even have a local hackage index to work with in the meantime.

**Comment by begriffs** [comment]
Thanks for this intermediate fix.

**Comment by afcowie** [comment]
> I'm sorry that I had no time to work on it yet, 

@aloiscochard hey man, there's no requirement for you to do anything. I'm so very pleased that you've heard out us asking for a new feature, and the fact that you've considered a way you might implement it and are intending to do so is fantastic.

Let us know if there's something we can do to help. Integrating stack and codex would make for a significant contribution to the Haskell ecosystem.

AfC

**Comment by aloiscochard** [comment]
@afcowie hey there! no worries, it's my pleasure to provide such a tool and that was actually a pretty good excuse for me to dive a bit more into `stack` (and also start using it!) which is a really nice piece of the ecosystem (and was badly needed!).

I now have a working implementation, that I personally use on my own projects, I would appreciate a bit of testing from others though, could you give `master` a try on your stack enabled project and let me know how it goes?

I'll do some testing as well, and aim to release `0.3.1` by the end of the week.

Thanks to all for your help and suggestions, especially @snoyberg one which I used to configure cabal (as a library) before running my usual code, for the record:
https://github.com/aloiscochard/codex/commit/fef651a72d74c7f417d0d47e997d6138b98a84f1#diff-170086a0872fa4c83b09f8bcd5bc838dR92

Using that approach, any tool that use cabal as a library can integrate `stack` support pretty easily imho.

It's always a pleasure to code with Haskell and contribute my humble pieces to the ecosystem :-)

**Comment by aloiscochard** [comment]
I did some more testing and added some fix (mostly related to stack having a different hackage index structure).

The latest release `0.4.0.0` is on hackage and have a complete transparent support for stack project.

**Comment by afcowie** [comment]
I love it when people release software faster than I can keep up with the GitHub mention asking me to have a look :) 

```
$ codex update
Configuring codex-0.4.0.1...
cabal: user error (The program 'ghc' version >=6.4 is required but it could not be found.)
codex: *warning* falling back on dependency resolution using hackage
Updating codex-0.4.0.1
```

Is that right @aloiscochard ? I really don't have GHC installed outside that which **stack** has provided to itself. It seems to have built a _codex.tags_ referencing _~/.stack_ content...

AfC

**Comment by aloiscochard** [comment]
@afcowie well sadly that's an edge case I did not faced before, so it did work somehow for you but by luck:
By following back on hackage resolution, you might have mismatch with version (codex might take a more recent version... same issue you had originally, the only difference is that now codex used the proper stack index for hackage).

I'm using the system GHC so I never faced that issue, and actually that won't be easy for now for me to debug this.

Simply because I'm using NixOS, and so far if `stack` try to use an "embedded" GHC it breaks ...

I'll add this as an improvement here for a second phase:
https://github.com/aloiscochard/codex/issues/46

In the meantime a workaround would be to install a system-level GHC to make cabal (the library) happy when configuring the project.

Maybe the fix is relatively trivial, I'm not sure how to configure cabal (using the same approach @snoyberg) in order for it to use the GHC configured by `stack`... that need investigation.

**Comment by afcowie** [comment]
@snoyberg would putting a symlink in _~/.local/bin_ called `ghc` to one of **stack**'s GHCs do the trick?
