### ISSUE TITLE
Codex automagically picks stack as a Builder

### ISSUE THREAD

**Issue by hasufell** [aloiscochard/codex#86]
https://github.com/aloiscochard/codex/blob/9ab9707fc67a56281910b2ab28784b0e35bae04b/codex/Main.hs#L158-L174

This shouldn't happen. Just because there is a stack file doesn't mean I actually want to use stack.

**Comment by parsonsmatt** [comment]
Should be fixed by #87

**Comment by vyorkin** [comment]
Another solution could be to have a CLI option / config parameter to manually specify the _builder_. Something like `codex set builder stack/cabal`.

The reason for this suggestion is that you might have a `.stack-work` dir even if you want to use cabal as a _bulider_ for `codex`. For example, currently if I have a `.stack-work` folder I get the following warnings and errors (for some reason):

```sh
codex: *warning* the following tags files where missings during assembly:
/home/vyorkin/.stack/indices/Hackage/packages/Cabal/3.0.1.0/tags
/home/vyorkin/.stack/indices/Hackage/packages/base/4.13.0.0/tags
```

```sh
"Codec.Compression.Zlib: compressed data stream format error (incorrect header check)"
```

So I have to remove the `.stack-work` to force the `cabal` _builder_ and the run the `codex update` command again.

In this particular case something like `builder` might be helpful. What do you think?

**Comment by parsonsmatt** [comment]
Patches welcome! I'd be happy to accept a CLI flag `--build-tool [cabal|stack]` that could override the default behavior.

It would appear that `base-4.30.0.0` and `Cabal-3.0.1.0` are not uploaded to Hackage. I don't know why.

Does using `cabal` as a build tool not have these errors/warnings?

(fwiw, you can just `mv .stack-work .stack-work-x` instead of the potentially costly deleting/rebuilding)

**Comment by vyorkin** [comment]
> Does using cabal as a build tool not have these errors/warnings?

Yeah, it works perfectly when I use cabal as a build tool.

Thanks @parsonsmatt! I'll try to submit a PR soon
